# Generated by Django 3.2.4 on 2021-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
